#!/usr/bin/env bash
# Credit: https://stackoverflow.com/questions/26624368/handle-multiple-pre-commit-hooks

cd "$(dirname "$0")/pre-push.d" || ( echo "Failed to cd to pre-push.d" && exit 1 )

errors=0

for hook in *; do
    bash "$hook"
    RESULT=$?
    if [ $RESULT != 0 ]; then
        echo "pre-push.d/$hook returned non-zero: $RESULT, abort push"
        errors+=1
    fi
done

if errors -gt 0;
then exit 1
else
  exit 0
fi
